export const INIT = '🎉 INIT'
export const COOKIE = '🍪 COOKIE'

export const LOGIN_REQUEST = '🛎 LOGIN_REQUEST'
export const LOGIN_SUCCESS = '✅ LOGIN_SUCCESS'
export const LOGIN_ERROR = '❌ LOGIN_ERROR'

export const LOGOUT = '👋 LOGOUT'

export const KEYCHAIN = '🔑 KEYCHAIN'
export const APPSTATE = '📱 APPSTATE'

export const PROFILE = '👤 PROFILE'

export const BACKGROUND = '⏰ BACKGROUND'
export const BACKGROUND_ERROR = '❌ BACKGROUND_ERROR'

export const CONVERSATION_REQUEST = '💬 CONVERSATION_REQUEST'
export const CONVERSATION_SUCCESS = '✅ CONVERSATION_SUCCESS'
export const CONVERSATIONS_REQUEST = '🗯 CONVERSATIONS_REQUEST'
export const CONVERSATIONS_SUCCESS = '✅ CONVERSATIONS_SUCCESS'

export const WEBSOCKET_CONNECTED = '📡 WEBSOCKET_CONNECTED'
export const WEBSOCKET_DISCONNECT = '👋️ WEBSOCKET_DISCONNECT'
export const WEBSOCKET_UNAUTHORIZED = '⛔️ WEBSOCKET_UNAUTHORIZED'
export const WEBSOCKET_ERROR = '❌ WEBSOCKET_ERROR'
export const WEBSOCKET_RECONNECT = '♻️ WEBSOCKET_RECONNECT'
export const WEBSOCKET_MESSAGE = '✉️ WEBSOCKET_MESSAGE'

export const MESSAGE_REQUEST = '✉️ MESSAGE_REQUEST'
export const MESSAGE_SUCCESS = '✅ MESSAGE_SUCCESS'

export const MARKERS_REQUEST = '🔰 MARKERS_REQUEST'
export const MARKERS_SUCCESS = '✅ MARKERS_SUCCESS'

export const FAIRTEILER_PREFETCH = '🦴 FAIRTEILER_PREFETCH'
export const FAIRTEILER_REQUEST = '♻️ FAIRTEILER_REQUEST'
export const FAIRTEILER_SUCCESS = '✅ FAIRTEILER_SUCCESS'

export const WALL_REQUEST = '📖 WALL_REQUEST'
export const WALL_SUCCESS = '✅ WALL_SUCCESS'
