export const INIT = '🎉 INIT'
export const COOKIE = '🍪 COOKIE'

export const REQUEST_ERROR = '❌ REQUEST_ERROR'

export const LOGIN_REQUEST = '🛎 LOGIN_REQUEST'
export const LOGIN_SUCCESS = '✅ LOGIN_SUCCESS'
export const LOGIN_ERROR = '❌ LOGIN_ERROR'

export const LOGOUT = '👋 LOGOUT'

export const NOTIFICATION_CLICKED = '📬 NOTIFICATION_CLICKED'

export const NAVIGATION = '🌐 NAVIGATION'
export const CONNECTION_STATUS = '📶 CONNECTION_STATUS'

export const KEYCHAIN = '🔑 KEYCHAIN'
export const BACKGROUND_STATE = '📱 BACKGROUND_STATE'

export const PROFILE = '👤 PROFILE'
export const PROFILE_REQUEST = '👤 PROFILE_REQUEST'
export const PROFILE_SUCCESS = '✅ PROFILE_SUCCESS'

export const FRIENDSHIP_REQUEST = '👤 FRIENDSHIP_REQUEST'
export const FRIENDSHIP_SUCCESS = '✅ FRIENDSHIP_SUCCESS'

export const REPORT_REQUEST = '🆘 REPORT_REQUEST'
export const REPORT_SUCCESS = '✅ REPORT_SUCCESS'

export const BACKGROUND_WAKEUP = '⏰ BACKGROUND_WAKEUP'
export const BACKGROUND_DONE = '✅ BACKGROUND_DONE'
export const BACKGROUND_ERROR = '❌ BACKGROUND_ERROR'

export const CONVERSATION_REQUEST = '💬 CONVERSATION_REQUEST'
export const CONVERSATION_SUCCESS = '✅ CONVERSATION_SUCCESS'
export const CONVERSATIONS_REQUEST = '🗯 CONVERSATIONS_REQUEST'
export const CONVERSATIONS_SUCCESS = '✅ CONVERSATIONS_SUCCESS'
export const CONVERSATION_ID_REQUEST = '🔎 CONVERSATION_ID_REQUEST'
export const CONVERSATION_ID_SUCCESS = '✅ CONVERSATION_ID_SUCCESS'

export const WEBSOCKET_CONNECTED = '📡 WEBSOCKET_CONNECTED'
export const WEBSOCKET_DISCONNECT = '👋️ WEBSOCKET_DISCONNECT'
export const WEBSOCKET_UNAUTHORIZED = '⛔️ WEBSOCKET_UNAUTHORIZED'
export const WEBSOCKET_ERROR = '❌ WEBSOCKET_ERROR'
export const WEBSOCKET_RECONNECT = '♻️ WEBSOCKET_RECONNECT'
export const WEBSOCKET_MESSAGE = '✉️ WEBSOCKET_MESSAGE'

export const MESSAGE_REQUEST = '✉️ MESSAGE_REQUEST'
export const MESSAGE_SUCCESS = '✅ MESSAGE_SUCCESS'
export const MESSAGE_READ = '📭️ MESSAGE_READ'

export const MARKERS_REQUEST = '📍 MARKERS_REQUEST'
export const MARKERS_SUCCESS = '✅ MARKERS_SUCCESS'

export const FAIRTEILER_PREFETCH = '🦴 FAIRTEILER_PREFETCH'
export const FAIRTEILER_REQUEST = '♻️ FAIRTEILER_REQUEST'
export const FAIRTEILER_SUCCESS = '✅ FAIRTEILER_SUCCESS'

export const WALL_REQUEST = '📖 WALL_REQUEST'
export const WALL_SUCCESS = '✅ WALL_SUCCESS'

export const BASKET_REQUEST = '🎁 BASKET_REQUEST'
export const BASKET_SUCCESS = '✅ BASKET_SUCCESS'
export const BASKETS_REQUEST = '🛍 BASKETS_REQUEST'
export const BASKETS_SUCCESS = '✅ BASKETS_SUCCESS'
export const BASKETS_NEARBY_REQUEST = '🔭 BASKETS_NEARBY_REQUEST'
export const BASKETS_NEARBY_SUCCESS = '✅ BASKETS_NEARBY_SUCCESS'
export const BASKET_ADD_REQUEST = '🎅 BASKET_ADD_REQUEST'
export const BASKET_ADD_SUCCESS = '✅ BASKET_ADD_SUCCESS'
export const BASKET_UPDATE_REQUEST = '♻️ BASKET_UPDATE_REQUEST'
export const BASKET_UPDATE_SUCCESS = '✅ BASKET_UPDATE_SUCCESS'
export const BASKET_UPLOAD_REQUEST = '📷 BASKET_UPLOAD_REQUEST'
export const BASKET_UPLOAD_SUCCESS = '✅ BASKET_UPLOAD_SUCCESS'
export const BASKET_DELETE_REQUEST = '🗑 BASKET_DELETE_REQUEST'
export const BASKET_DELETE_SUCCESS = '✅ BASKET_DELETE_SUCCESS'
